### PR TITLE
update Changelog

### PR DESCRIPTION
**Pull request by nicraMarcin**

### CODE REVIEW

**Comment by zlyZwierz** [comment]
Sure about this bitmap numbers? 1 2 5 7?
 16 kwi 2015 18:34 "Tomasz Chiliński" <notifications@github.com> napisał(a):

**Comment by nicraMarcin** [comment]
1 2 4 8, like bitmap
16 kwi 2015 19:18 "zlyZwierz" <notifications@github.com> napisał(a):

**Comment by zlyZwierz** [comment]
In the changelog.
16 kwi 2015 19:50 "nicraMarcin" <notifications@github.com> napisał(a):

**Comment by nicraMarcin** [comment]
It was corrected.

2015-04-16 20:50 GMT+02:00 zlyZwierz <notifications@github.com>:

> In the changelog.
>
> 16 kwi 2015 19:50 "nicraMarcin" <notifications@github.com> napisał(a):
>
> > 1 2 4 8, like bitmap
> > 16 kwi 2015 19:18 "zlyZwierz" <notifications@github.com> napisał(a):
> >
> > > Sure about this bitmap numbers? 1 2 5 7?
> > > 16 kwi 2015 18:34 "Tomasz Chiliński" <notifications@github.com>
> > > napisał(a):
> > >
> > > > Merged #340 <https://github.com/lmsgit/lms/pull/340>.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/lmsgit/lms/pull/340#event-283217728>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/lmsgit/lms/pull/340#issuecomment-93789026>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lmsgit/lms/pull/340#issuecomment-93800459>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lmsgit/lms/pull/340#issuecomment-93813393>.
>



-- 
Pozdrawiam
Marcin / nicraM

**Comment by chilek** [comment]
Actually it has been removed in next commit.

**Pull request merged**
